name: Minecraft | Slocraft/Notsitz
description: Newsticker für Slocraft/Minecraft-Notsitz
url: http://mc.notsitz.info

markdown: redcarpet
pygments: true
encoding: UTF-8
exclude: [Rakefile, Gemfile, Gemfile.lock]
